### ISSUE TITLE
NameError with SCAN_GENERATED_PLIST_FILE

### ISSUE THREAD

**Issue by lyricsboy** [KrauseFx/trainer#3]
I'm using:
* trainer 0.2.0
* fastlane 1.99.0
* scan 0.10.1

When attempting to run trainer within fastlane, I get the following error:

```
fastlane-plugin-trainer-0.2.0/lib/fastlane/plugin/trainer/actions/trainer_action.rb:7:in `run': [!] uninitialized constant Fastlane::Actions::SharedValues::SCAN_GENERATED_PLIST_FILE (NameError)
```

Does [this code](https://github.com/KrauseFx/trainer/blob/master/fastlane-plugin-trainer/lib/fastlane/plugin/trainer/actions/trainer_action.rb#L7) depend on a version of something newer that I don't have? What could be the issue here?

**Comment by lyricsboy** [comment]
Updating to fastlane 1.100.0 and scan 0.11.2 resolved the issue for me.

**Comment by KrauseFx** [comment]
Thanks for letting me know - seems like the dependency wasn't properly updated
