### ISSUE TITLE
Unable to resolve dependencies on install

### ISSUE THREAD

**Issue by srking** [KrauseFx/trainer#8]
Attempting to install trainer fails, as the required dependencies cannot be found.

Gemfile:
> source "https://rubygems.org"
> gem 'trainer'

Running `bundle install` fails with the following error:

> Bundler could not find compatible versions for gem "credentials_manager":
> &nbsp;&nbsp;In Gemfile:
> &nbsp;&nbsp;&nbsp;&nbsp;trainer was resolved to 0.1.1, which depends on
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fastlane_core (< 1.0.0, >= 0.48.1) was resolved to 0.48.1, which depends on
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;credentials_manager (< 1.0.0, >= 0.16.0)
> 
> Could not find gem 'credentials_manager (< 1.0.0, >= 0.16.0)', which is required by gem 'fastlane_core (< 1.0.0, >= 0.48.1)', in any of the sources.

Similar errors occurred when I specified a version number in the Gemfile.

**Comment by KrauseFx** [comment]
Looking into this right now, sorry for the delay

**Comment by KrauseFx** [comment]
Just pushed the new release, please let me know if that works for you 👍

**Comment by srking** [comment]
This has fixed the issue for me. Many thanks!
