### ISSUE TITLE
Cannot load such file -- fastlane_core (LoadError)

### ISSUE THREAD

**Issue by maxfriedrich** [KrauseFx/trainer#9]
I'm using trainer 0.5.0 standalone (not as a fastlane plugin). I'm using RVM ruby and installing the gem with `bundle`.

I get this output:
```
$ bundle exec trainer
/Users/max.friedrich/.rvm/gems/ruby-2.3.1/gems/trainer-0.5.0/lib/trainer.rb:1:in `require': cannot load such file -- fastlane_core (LoadError)
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/gems/trainer-0.5.0/lib/trainer.rb:1:in `<top (required)>'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/gems/trainer-0.5.0/bin/trainer:4:in `require'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/gems/trainer-0.5.0/bin/trainer:4:in `<top (required)>'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/bin/trainer:22:in `load'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/bin/trainer:22:in `<main>'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/max.friedrich/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

`fastlane_core` is indeed `require`d in [`lib/trainer.rb`](https://github.com/KrauseFx/trainer/blob/b1727810b586c10c5f00684e4ec5a410c93582ba/lib/trainer.rb#L1) but was [recently removed](https://github.com/KrauseFx/trainer/commit/aad647bd13b43b633b915cb310ccf80d07ea4a22#diff-88415f93e551a1cb640b74c920e4727c) as a dependency in `trainer.gemspec`.

**Comment by KrauseFx** [comment]
fastlane core is now part of fastlane. Can you share your `Gemfile`? Does it include the `fastlane` gem as dependency?

**Comment by SoneeJohn** [comment]
@maxfriedrich I had this same issue. I solved it by installing fastlane with: ```sudo gem install fastlane -NV``

**Comment by maxfriedrich** [comment]
Ah, thanks! I don't have `fastlane` in my `Gemfile`. But if it's indeed a requirement, it should be added to `trainer.gemspec`, right?

**Comment by KrauseFx** [comment]
@maxfriedrich actually that can't be done, as it would have a circular dependency then as soon as you add the pilot plugin. Instead you have to use a Gemfile anyway once you use fastlane with plugins 👍

**Comment by maxfriedrich** [comment]
OK! Thanks! 👍
